---

- meta: flush_handlers

- name: Create network
  become: true
  docker_network:
    name: "{{ item.name }}"
  with_items: "{{ mattermost_docker_networks }}"

- name: Start or restart mattermost db container
  become: true
  docker_container:
    name: "{{ mattermost_db_container_name }}"
    image: mattermost/mattermost-prod-db
    state: "{{ mattermost_docker_state | default('started') }}"
    restart: "{{ mattermost_db_docker_restart | default(false) | bool }}"
    networks: "{{ mattermost_docker_networks }}"
    restart_policy: "{{ mattermost_container_restart_policy }}"
    volumes:
      - "{{ mattermost_postgres_data_location }}:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: "{{ secrets_json.PostgresPassword}}"
      POSTGRES_DB: mattermost

- name: Start or restart mattermost app container
  become: true
  docker_container:
    name: "{{ mattermost_app_container_name }}"
    image: bastienf/mattermost-app-prod
    state: "{{ mattermost_docker_state | default('started') }}"
    restart: "{{ mattermost_app_docker_restart | default(false) | bool }}"
    networks: "{{ mattermost_docker_networks }}"
    restart_policy: "{{ mattermost_container_restart_policy }}"
    volumes:
      - "{{ mattermost_app_conf_location }}:/mattermost/config:ro"
      - "{{ mattermost_app_data_location }}:/mattermost/data:rw"
      - "{{ mattermost_app_logs_location }}:/mattermost/logs:rw"
      - "{{ mattermost_plugins_location }}:/mattermost/plugins:rw"
      - /etc/localtime:/etc/localtime:ro
    env:
      # set same as db credentials and dbname
      MM_USERNAME: mmuser
      MM_PASSWORD: "{{ secrets_json.PostgresPassword}}"
      MM_DBNAME: mattermost
      DB_HOST: "{{ mattermost_db_container_name }}"
