---

mattermost_user_app_config:
  ServiceSettings: {}
  TeamSettings: {}
  PasswordSettings: {}
  EmailSettings: {}
  PrivacySettings: {}
  SupportSettings: {}
  LocalizationSettings: {}
  DataRetentionSettings: {}
#mattermost_user_app_config:
#  ServiceSettings:
#    SiteURL: ''
#    WebsocketURL: ''
#    MaximumLoginAttempts: 10
#    EnableOAuthServiceProvider: false
#    EnableCustomEmoji: false
#    EnableEmojiPicker: true
#    EnableGifPicker: false
#    AllowEditPost: always
#    PostEditTimeLimit: -1
#    EnableEmailInvitations: false
#  TeamSettings:
#    SiteName: Mattermost
#    MaxUsersPerTeam: 50
#    EnableTeamCreation: true
#    EnableUserCreation: true
#    EnableOpenServer: false
#    EnableUserDeactivation: false
#    RestrictCreationToDomains: ''
#    CustomBrandText: ''
#    CustomDescriptionText: ''
#    RestrictDirectMessage: any
#    RestrictTeamInvite: all
#    RestrictPublicChannelManagement: all
#    RestrictPrivateChannelManagement: all
#    RestrictPublicChannelCreation: all
#    RestrictPrivateChannelCreation: all
#    RestrictPublicChannelDeletion: all
#    RestrictPrivateChannelDeletion: all
#    RestrictPrivateChannelManageMembers: all
#    EnableXToLeaveChannelsFromLHS: false
#    UserStatusAwayTimeout: 300
#    MaxChannelsPerTeam: 2000
#    MaxNotificationsPerChannel: 1000
#    EnableConfirmNotificationsToChannel: true
#    TeammateNameDisplay: username
#    ExperimentalViewArchivedChannels: false
#    ExperimentalEnableAutomaticReplies: false
#    ExperimentalHideTownSquareinLHS: false
#    ExperimentalTownSquareIsReadOnly: false
#    ExperimentalPrimaryTeam: ''
#    ExperimentalDefaultChannels: []
#  PasswordSettings:
#    MinimumLength: 6
#    Lowercase: false
#    Number: false
#    Uppercase: false
#    Symbol: false
#  EmailSettings:
#    EnableSignUpWithEmail: true
#    EnableSignInWithEmail: true
#    EnableSignInWithUsername: true
#    SendEmailNotifications: false
#    UseChannelInEmailNotifications: false
#    RequireEmailVerification: false
#    FeedbackName: ''
#    FeedbackEmail: ''
#    FeedbackOrganization: ''
#    EnableSMTPAuth: false
#    SMTPUsername: ''
#    SMTPPassword: ''
#    SMTPServer: ''
#    SMTPPort: ''
#    ConnectionSecurity: ''
#    SendPushNotifications: false
#    PushNotificationServer: ''
#    PushNotificationContents: generic
#    EnableEmailBatching: false
#    EmailBatchingBufferSize: 256
#    EmailBatchingInterval: 30
#    EnablePreviewModeBanner: true
#    SkipServerCertificateVerification: false
#    EmailNotificationContentsType: full
#    LoginButtonColor: ''
#    LoginButtonBorderColor: ''
#    LoginButtonTextColor: ''
#  PrivacySettings:
#    ShowEmailAddress: true
#    ShowFullName: true
#  SupportSettings:
#    TermsOfServiceLink: https://about.mattermost.com/default-terms/
#    PrivacyPolicyLink: https://about.mattermost.com/default-privacy-policy/
#    AboutLink: https://about.mattermost.com/default-about/
#    HelpLink: https://about.mattermost.com/default-help/
#    ReportAProblemLink: https://about.mattermost.com/default-report-a-problem/
#    SupportEmail: feedback@mattermost.com
#  LocalizationSettings:
#    DefaultServerLocale: en
#    DefaultClientLocale: en
#    AvailableLocales: ''
#  DataRetentionSettings:
#    EnableMessageDeletion: false
#    EnableFileDeletion: false
#    MessageRetentionDays: 365
#    FileRetentionDays: 365
#    DeletionJobStartTime: '02:00'